import { Urbanist } from "next/font/google";
import "./globals.css";
import { LenisProvider } from "@/components/utils/LenisProvider";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Toaster } from "sonner";
import { fetchFromAPI } from "@/lib/api";
import Error from "./error";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "GO EC",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const {data, error} = await fetchFromAPI("header-footer")


  const {header_section, footer_section} = data


  return (
    // <LenisProvider>
      <html lang="en">
        <body className={`${urbanist.className} antialiased`}>
          <Header header_section={header_section} />
          <main>{children}</main>
          <Footer footer_section={footer_section}/>
          <Toaster position="top-right" richColors />
        </body>
      </html>
    // {/* </LenisProvider> */}
  );
}
