import { Urbanist } from "next/font/google";
import "./globals.css";
import { LenisProvider } from "@/components/utils/LenisProvider";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "GO EC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <LenisProvider>
      <html lang="en">
        <body className={`${urbanist.className} antialiased`}>
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </LenisProvider>
  );
}
